(define (problem run-generator2)
    (:domain generator_linear)
    (:objects gen - generator tank1 tank2 tank3 tank4 tank5 tank6 - tank)
    (:init
		(= (fuelLevel gen)  900)
		(= (capacity gen)  1000)
		(on gen)
		(at 1.0 (not (on gen)))
		(not (available tank1))
		(not (available tank2))
		(not (available tank3))
		(not (available tank4))
		(not (available tank5))
		(not (available tank6))
		(at 50.0 (available tank1))
		(at 51.0 (not (available tank1)))
		(at 100.0 (available tank2))
		(at 101.0 (not (available tank2)))
		(at 150.0 (available tank3))
		(at 151.0 (not (available tank3)))
		(at 200.0 (available tank3))
		(at 201.0 (not (available tank3)))
		(at 250.0 (available tank4))
		(at 251.0 (not (available tank4)))
		(at 300.0 (available tank5))
		(at 301.0 (not (available tank5)))
		(at 350.0 (available tank6))
		(at 351.0 (not (available tank6)))
    )  
	(:goal (generator-ran))
)