(define (problem run-generator2)
    (:domain generator_linear)
    (:objects gen - generator tank1 tank2 tank3 tank4 - tank)
    (:init
		(= (fuelLevel gen)  920)
		(= (capacity gen)  1000)
		(on gen)
		(at 1.0 (not (on gen)))
		(not (available tank1))
		(not (available tank2))
		(not (available tank3))
		(not (available tank4))
		(at 50.0 (available tank1))
		(at 51.0 (not (available tank1)))
		(at 100.0 (available tank2))
		(at 101.0 (not (available tank2)))
		(at 150.0 (available tank3))
		(at 151.0 (not (available tank3)))
		(at 200.0 (available tank4))
		(at 201.0 (not (available tank4)))
    )  
	(:goal (generator-ran))
)