(define (problem run-generator2)
    (:domain generator_linear)
    (:objects gen - generator tank1 - tank)
    (:init
		(= (fuelLevel gen)  990)
		(= (capacity gen)  1000)
		(not (available tank1))
		(at 10.0 (available tank1))
    )  
	(:goal (generator-ran))
)